In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [2]:
df = pd.read_csv("D:\PowerBI Projects\Pharma_Dashboard\Data\pharma-data.csv")

df.head()

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_7804\2516588688.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("D:\PowerBI Projects\Pharma_Dashboard\Data\pharma-data.csv")

,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,Product Name,Product Class,Quantity,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team
0,Gottlieb-Cruickshank,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,Topipizole,Mood Stabilizers,4.0,368,1472.0,January,2018,Mary Gerrard,Britanny Bold,Delta
1,Gottlieb-Cruickshank,Feest PLC,Świecie,Poland,53.4167,18.4333,Pharmacy,Retail,Choriotrisin,Antibiotics,7.0,591,4137.0,January,2018,Jessica Smith,Britanny Bold,Delta
2,Gottlieb-Cruickshank,Medhurst-Beer Pharmaceutical Limited,Rybnik,Poland,50.0833,18.5000,Pharmacy,Institution,Acantaine,Antibiotics,30.0,66,1980.0,January,2018,Steve Pepple,Tracy Banks,Bravo
3,Gottlieb-Cruickshank,Barton Ltd Pharma Plc,Czeladź,Poland,50.3333,19.0833,Hospital,Private,Lioletine Refliruvax,Analgesics,6.0,435,2610.0,January,2018,Mary Gerrard,Britanny Bold,Delta
4,Gottlieb-Cruickshank,Keeling LLC Pharmacy,Olsztyn,Poland,53.7800,20.4942,Pharmacy,Retail,Oxymotroban Fexoformin,Analgesics,20.0,458,9160.0,January,2018,Anne Wu,Britanny Bold,Delta

In [3]:
print("Shape :", df.shape)

Shape : (254082, 18)

In [4]:
print("\nColumns:")
print(df.columns.tolist())

Columns:
['Distributor', 'Customer Name', 'City', 'Country', 'Latitude', 'Longitude', 'Channel', 'Sub-channel', 'Product Name', 'Product Class', 'Quantity', 'Price', 'Sales', 'Month', 'Year', 'Name of Sales Rep', 'Manager', 'Sales Team']

In [5]:
print("\nData Types:")
print(df.dtypes)

Data Types:
Distributor           object
Customer Name         object
City                  object
Country               object
Latitude             float64
                      ...
Month                 object
Year                   int64
Name of Sales Rep     object
Manager               object
Sales Team            object
Length: 18, dtype: object

In [8]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})

# missing = missing[missing["Missing Values"] > 0]

# missing.sort_values("Percentage", ascending=False)
df.isnull().sum()
display(missing.sort_values("Percentage", ascending=False))

                   Missing Values  Percentage
Distributor                     0         0.0
Customer Name                   0         0.0
City                            0         0.0
Country                         0         0.0
Latitude                        0         0.0
...                           ...         ...
Month                           0         0.0
Year                            0         0.0
Name of Sales Rep               0         0.0
Manager                         0         0.0
Sales Team                      0         0.0

[18 rows x 2 columns]

In [9]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

df.drop_duplicates(inplace=True)

print("Duplicates Removed!")

Duplicate Rows : 4
Duplicates Removed!

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Latitude,254078.0,50.962216,1.625536,4.751420e+01,49.8056,51.1333,52.0833,5.478190e+01
Longitude,254078.0,10.803216,4.143295,6.083800e+00,7.8911,9.3978,12.1333,2.356670e+01
Quantity,254078.0,112.873680,744.316142,-7.200000e+03,5.0000,20.0000,50.0000,1.176000e+05
Price,254078.0,412.210510,224.963357,2.200000e+01,195.0000,430.0000,605.0000,7.940000e+02
Sales,254078.0,46438.407663,349194.543384,-4.161600e+06,1704.0000,5850.0000,21591.7500,7.420560e+07
Year,254078.0,2018.385193,1.041356,2.017000e+03,2018.0000,2018.0000,2019.0000,2.020000e+03

In [11]:
for col in df.select_dtypes(include="object"):
    print(f"\n{col}")
    print(df[col].nunique())

Distributor
29

Customer Name
751

City
749

Country
2

Channel
2

Sub-channel
4

Product Name
240

Product Class
6

Month
12

Name of Sales Rep
13

Manager
4

Sales Team
4

In [12]:
# Replace "Date" with your column name

if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"])

In [13]:
obj_cols = df.select_dtypes(include="object").columns

for col in obj_cols:
    df[col] = df[col].str.strip()

In [14]:
df.to_csv("D:/PowerBI Projects/Pharma_Dashboard/Data/cleaned_pharma_sales.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!